### ISSUE TITLE
Builder prefixes

### ISSUE THREAD

**Issue by janishorsts** [expect-digital/go-mf2#24]
Currently, the builder requires prefixes for variables, functions and keywords. The reason is functions that have a wide range of prefixes, we would need to create a build step for each function to identify its type.

The Message Format 2 requires the following prefixes:

* `.` for keywords
* `$` for variables
* `:`, `+` and `-` for functions

Keyword build steps already add keywords - no changes required.

# Suggested resolutions.

## var

```go
// PREVIOUSLY, "s" must be prefixed with "$"
func Var(s string) *Expression

// SUGGESTED SOLUTION

// builder prefixes with "$", rename "s" to "name"
func Var(name string) *Expression
```
The same change applies to the receiver function.

## func

```go
// PREVIOUSLY, "name" must be prefixed with "+", "-" or ":"
func Func(name string, option ...FuncOption) *Expression

// SUGGESTED SOLUTION

// builder prefixes with "+"
func OpenFunc(name string, option ...FuncOption) *Expression

// builder prefixes with "-"
func CloseFunc(name string, option ...FuncOption) *Expression

// builder prefixes with ":"
func Func(name string, option ...FuncOption) *Expression
```
The same change applies to the receiver functions.

## private keywords

No changes are required for keywords. The private keyword is not implemented yet.

## option

// current implementation is not correct. There is no way to determine if the operand is literal or variable
func Option(name string, operand any) FuncOption {}

// SUGGESTED SOLUTION

func VarOption(name, varName string) FuncOption
func LiteralOption(name string, value any) FuncOption

**Comment by janishorsts** [comment]
In this instance, a smaller code is better. But I like your thinking.

**Comment by janishorsts** [comment]
```go
// current implementation is not correct. There is no way to determine if the operand is literal or variable
func Option(name string, operand any) FuncOption {}

// SUGGESTED SOLUTION #1

func Option(name string) FuncOption
func (o FuncOption) Literal(value any) FuncOption
func (o FuncOption) Var(name any) FuncOption

// SUGGESTED SOLUTION #2

func VarOption(name, varName string) FuncOption
func LiteralOption(name string, value any) FuncOption
```

**Comment by klavinsjanis** [comment]
SUGGESTED SOLUTION #2 looks alright

**Comment by VladislavsPerkanuks** [comment]
Second is the most KISS, so I would go with that

**Comment by VladislavsPerkanuks** [comment]
The sad thing is that only time and experience can tell, which would be best for us to use :)
