### ISSUE TITLE
Update to the latest MF2 ABNF definition

### ISSUE THREAD

**Issue by janishorsts** [expect-digital/go-mf2#34]

**Comment by VladislavsPerkanuks** [comment]
[Diff](https://github.com/unicode-org/message-format-wg/compare/86cc16b05a86214c22233f71efe18ef1c162c220..f9b0c6fde345e936cc7f06835ad138d6c056d63a#diff-a33e1c859f2aaad86b37ea3b3b5e8d45331199d6e879c5aba38eca2f23f01865): our current vs newset

**Comment by VladislavsPerkanuks** [comment]
This is better diff, only the abnf and ignored whitespace for better readability
https://www.diffchecker.com/tyXs3dCp/
